build_html:
  image: docker-registry.csc.mpi-magdeburg.mpg.de:5000/ci-images/minimal/latex:focal
  before_script:
    # Download and install pandoc 
    - wget https://github.com/jgm/pandoc/releases/download/2.17.1.1/pandoc-2.17.1.1-1-amd64.deb
    - dpkg -i pandoc-2.17.1.1-1-amd64.deb
    - apt-get update -y
    - apt-get install -y vim
    # - apt-get update -y
    # - apt-get install -y pandoc
    # - apt-get install -y pandoc-citeproc
  script:
    - source mkdc.sh
    - pandoc --version >> pdv.txt
  artifacts:
    paths:
      - "slides.html"
      - "slides.pdf"
      - "slides.tex"
      - "slides-body.tex"
      - "pics"
      - "theme-pics"
      - "pdv.txt"
